name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".gitignore"

concurrency:
  group: build
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image:
          - name: clang-20-conan-aui
            dockerfile: clang-20-conan-aui/Dockerfile
          - name: gcc-15-conan-aui
            dockerfile: gcc-15-conan-aui/Dockerfile
          - name: ndk-28b-conan-aui
            dockerfile: NDK-28b-conan-aui/Dockerfile

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Set lowercase repository owner
        run: |
          echo "REPOSITORY_OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER_LC }}/${{ matrix.image.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
